services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    networks:
      - gielda_network
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "2g"
        reservations:
          cpus: "2.0"
          memory: "1g"

  redis:
    image: redis:latest
    networks:
      - gielda_network
    ports:
      - "6379:6379"

  db_test:
    image: postgres:14
    networks:
      - gielda_network
    environment:
      POSTGRES_DB: test_stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "6544:5432"

  web:
    build: .
    command: 
      sh -c 
      "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py migrate --database=test &&
      python manage.py collectstatic --noinput &&
      gunicorn stockProject.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - db_test
    environment:
      ENV_ID: "web"
      TRANSACTION_TIME: "15.0"
    networks:
      - gielda_network
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "2g"
        reservations:
          cpus: "2.0"
          memory: "1g"
  
  celery_worker_schedule_transactions:
    build: .
    command: 
      celery -A stockProject worker -l info -Q transactions -P gevent     
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - db_test
    networks:
      - gielda_network
    environment:
      ENV_ID: "celery_worker_schedule_transactions"
      TRANSACTION_TIME: "15.0"

  celery_worker_execute_transactions:
    build: .
    command:
      celery -A stockProject worker -l info -P gevent
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - db_test
    networks:
      - gielda_network
    environment:
      ENV_ID: "celery_worker_execute_transactions"
      TRANSACTION_TIME: "15.0"
    deploy:
      replicas: 4  #  worker dedykowany do przetwarzania transakcji

  monitor:
    build: ./monitor
    environment:
      DB_HOST: db_test
      DB_NAME: test_stock
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./monitor:/app  # Zakładając, że pliki monitorujące są w folderze "monitoring"
      - /var/run/docker.sock:/var/run/docker.sock  # Udostępnienie Docker sock
    depends_on:
      - db
      - db_test
    networks:
      - gielda_network
    command: ["python", "/app/monitor.py"]

  celery_worker_balance_updates:
    build: .
    command:      
      celery -A stockProject worker -l info -Q balance_updates -P gevent
    volumes:
      - .:/app
    networks:
      - gielda_network
    environment:
      ENV_ID: "celery_worker_balance_updates"
      TRANSACTION_TIME: "15.0"
    depends_on:
      - db
      - redis
      - db_test

  celery_worker_stock_rates:
    build: .
    command:
      celery -A stockProject worker -l info -Q stock_rates -P gevent
    volumes:
      - .:/app
    networks:
      - gielda_network
    environment:
      ENV_ID: "celery_worker_stock_rates"
      TRANSACTION_TIME: "15.0"
    depends_on:
      - db
      - redis
      - db_test

  celery_worker_expire_offers:
    build: .
    command:      
      celery -A stockProject worker -l info -Q expire_offers -P gevent
    volumes:
      - .:/app
    networks:
      - gielda_network
    environment:
      ENV_ID: "celery_worker_expire_offers"
      TRANSACTION_TIME: "15.0"
    depends_on:
      - db
      - redis
      - db_test

  celery_beat:
    build: .
    command:
      celery -A stockProject beat --loglevel=info
    volumes:
      - .:/app
    networks:
      - gielda_network
    environment:
      ENV_ID: "celery_beat"
      TRANSACTION_TIME: "15.0"
    depends_on:
      - db
      - redis
      - db_test

  locust:
    build: ../loadTestingApp  # ścieżka do nowego projektu
    command: /app/start_locust.sh
    ports:
      - "8089:8089"
    networks:
      - gielda_network
    environment:
      ENV_ID: "locust"
      LOCUST_TIME: "10m"
    depends_on:
      - web
      - db
      - db_test

volumes:
  postgres_data:
  postgres_test_data:
networks:
  gielda_network:
    driver: bridge