# Generated by Django 5.0.6 on 2024-07-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
