# Generated by Django 5.0.6 on 2024-07-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_transaction_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='selloffer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockApp.company'),
            preserve_default=False,
        ),
    ]
