# Generated by Django 5.0.6 on 2024-07-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_alter_transaction_transaciondate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='money',
            new_name='amount',
        ),
    ]
