# Generated by Django 5.0.6 on 2024-08-16 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0005_rename_money_stock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moneyAfterTransations',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='BalanceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.FloatField()),
                ('change_type', models.CharField(choices=[('money', 'Money'), ('moneyAfterTransactions', 'Money After Transactions')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
