# Generated by Django 5.0.6 on 2024-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0006_customuser_moneyaftertransations_balanceupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceupdate',
            name='actual',
            field=models.BooleanField(default=True),
        ),
    ]
